### ISSUE TITLE
Allow node labels to be templates

### ISSUE THREAD

**Issue by nrbgt** [jupyrdf/ipyforcegraph#10]
## Elevator Pitch

Instead of a single column, node labels could be composed on the front end from many columns.

## Motivation

The return value of `nodeLabel` can be an HTML string, and might be interesting to have more data. With access to the node and full graph data, one could print out some nice values, including:
- images
- information about linked values
- inline CSS

## References

- blocked by #4

## Design Idea

- add a `template` 
  - a jinja2/[nunjucks](https://mozilla.github.io/nunjucks/templating.html) template that gets access to the `node` and the `graphData`

**Comment by sanbales** [comment]
Wonder if we should rename this behavior from `NodeLabels` to `NodeTooltip` to avoid confusion with the node shape being changed to the text label.
