### ISSUE TITLE
Non-string `Text.text` values crash `ipyforcegraph`

### ISSUE THREAD

**Issue by sanbales** [jupyrdf/ipyforcegraph#103]
## Description

In [this line](https://github.com/jupyrdf/ipyforcegraph/blob/ff2af937b898e2ead158d4de2669b5b44c28dacf/js/widgets/behaviors/shapes/text.ts#L50C28-L50C28) we don't check to see if `drawOptions.text` is a string, and if it is set to something else (e.g., a number), the `ForceGraph` will crash, producing the following error.

```
text.ts:50 Uncaught TypeError: o.text.trim is not a function
```

The error seems to be not recoverable, i.e., only way to get the graph to render again is to make a new ForceGraph.  Also, errors only show up in the JavaScript Console.

## Reproduce

1. Make a dataframe for the `nodes` that has as numeric value
2. Create a `NodeShape` behavior and use `Text` as the shape
3. Assign the `.text` property using a `Column(<non-text-attribute>)`

## Expected behavior

Would expect non-text values to be cast to strings.

**Comment by nrbgt** [comment]
Fixed by #104
