### ISSUE TITLE
Option to Store Computed Colors on `nodes` and `links`

### ISSUE THREAD

**Issue by sanbales** [jupyrdf/ipyforcegraph#123]
## Elevator Pitch

* Like with `NodeSelection` and `LinkSelection`, add an option to `ContinuousColor` and `OrdinalColor` to store the value in a column.

## Motivation

* We want to be able to color `links` based on the color of their `source` or `target`, but when the `nodes` are colored using `ContinuousColor`, it is not possible to reference a `node`'s color.
* This is motivated from the concept of groups in a graph, where we not only want to color the `nodes` based on their group assignment, but also the `links` that connect between two `nodes` in the same group.

## Design Ideas

* Add a `column_name` trait to `ContinuousColor` and `OrdinalColor` and store the computed color under that name,
* As with `NodeSelection` and `LinkSelection`, the `default_value = None` and in which case, nothing is stored.
* We may want to check that the user does not specify `__indexColor` as that seems to be a reserved property in `forcegraph`.

**Comment by nrbgt** [comment]
Fixed by #125
