### ISSUE TITLE
Adjust Color Palette based on Lightness/Contrast

### ISSUE THREAD

**Issue by sanbales** [jupyrdf/ipyforcegraph#129]
# Elevator Pitch

Parameterize the palettes so that they can automatically adapt to the dark/light themes.

# Motivation

Some colors in the palettes are hard to see in either light mode or dark mode (sometimes both). For example, purple (shown below) is difficult to see against dark gray.

![image](https://github.com/jupyrdf/ipyforcegraph/assets/1438114/2a80f9f6-0df6-419a-b64d-1b43d3000e70)

# Design Ideas    

- Wrap ordinal color scales by converting them to HSL and controlling the lightness parameter. This way, we can adjust the lightness when toggling dark mode / light mode.
- Calculate the contrast of the colors in the palette relative to the background color, and then limiting the range of colors in the palette to those that have a minimum relative contrast value.

**Comment by sanbales** [comment]
@nrbgt : We are spitballing here but it would be a very nice feature to have from a user experience perspective.  Not sure if these ideas are the right ones, or if there is an easier/better way to accomplish this.

**Comment by nrbgt** [comment]
Fixed by #131,
