### ISSUE TITLE
Sync front-end when `nodes` & `links` are updated in `DataFrameSource`

### ISSUE THREAD

**Issue by sanbales** [jupyrdf/ipyforcegraph#13]
# Issue
Right now, even if one makes a new `DataFrame` for the `nodes` or `links` in a `DataFrameSource`, the data does not get propagated to the front-end.  This may be by design or something that has not yet been implemented. 

# Replication

```python
import json
from pathlib import Path

import ipywidgets as W

from ipyforcegraph.forcegraph import DataFrameSource, ForceGraph

def make_a_simple_example(
    source=None, dataset="datasets/miserables.json", GraphClass=ForceGraph, node_color=None,
):
    if source is None:
        data = json.loads(Path(dataset).read_text())
        source = DataFrameSource(**data)
        if node_color:
            source.nodes["color"] = node_color

    fg = GraphClass(source=source, layout=dict(height="500px"))
    box = W.HBox([fg, W.VBox([])])
    return fg, box

if __name__ == "__main__":
    fg, box = make_a_simple_example(node_color="red")
    display(box)
```

Nodes should be `red` but they show up the default `steelblue`.  If a new `source` is made, or we run `fg.source.send_state()` the nodes show up `red`.

# Design Ideas
- It would be preferred if it didn't re-solve the positions of the nodes if it is the same set of nodes (e.g., have the same `id`s?)
  - maybe we can try to get the existing nodes in [here](https://github.com/jupyrdf/ipyforcegraph/blob/main/js/widgets/sources/dataframe.ts#L75) if the `node`'s `id` match?

# Related to
- #9 ?

**Comment by nrbgt** [comment]
To my knowledge, there's no way to instrument a dataframe for changes.

In the demos, i've been using `fg.source.send_state("nodes")` to force updating. We could add some sugar for this, i suppose, but it's not the worst thing in the world for it to be rather intentional.

**Comment by sanbales** [comment]
That's a good point.  Maybe it is just documentation or adding a method at the `forcegraph` level to make it easier for the neophytes, e.g.,

```python
def update_source(self, *states: str):
  states = states or ("nodes", "links")
  with self.source.hold_sync():
    for state in states:
      self.source.send_state(state)
```
