### ISSUE TITLE
`conda` packaging

### ISSUE THREAD

**Issue by sanbales** [jupyrdf/ipyforcegraph#17]
# 🗣️ Elevator Pitch
There are enough capabilities to merit making this conda installable.

# 🏃 Motivation
Other projects can start testing the library, but it'd make it easier for them to do that if they could `conda install ipyforcegraph`.

# 💡 Design Ideas
* Submit a new recipe to `conda-forge`

**Comment by nrbgt** [comment]
I think we need at least _minimal_ robot tests (run notebooks, see no tracebacks, some canvas exists) before confidently shipping. But sure.

**Comment by sanbales** [comment]
Absolutely, and absolute respect for the commitment to code quality.  I know we have 🤖 running the notebooks, but should we make a separate ticket to check the canvas exists and there are no tracebacks?

**Comment by nrbgt** [comment]
https://github.com/conda-forge/staged-recipes/pull/21799

**Comment by nrbgt** [comment]
:point_up: was merged, but there's a big backlog due to some resource exhaustion issues (CI tokens). hopefully up some time today. we could just go ahead and drop 0.2.0 on pypi.

**Comment by nrbgt** [comment]
https://anaconda.org/conda-forge/ipyforcegraph/files?version=0.1.0
