### ISSUE TITLE
Tunable d3 forceLayout

### ISSUE THREAD

**Issue by dfreeman06** [jupyrdf/ipyforcegraph#28]
## Elevator Pitch

Force layout diagrams will be more flexible by exposing some of the underlying `forceLayout` simulation parameters. Specifically the d3Forces `link`, `charge` and `center` can enable tuning of the layout based on communities in the graph. 

## Motivation

This will let users tune their simulation engine to generate more nuanced layouts. 
* Different link strengths based on edge weight.
* Grouping clusters of nodes based on similarity

## Design Ideas
Examples
* [Multi-Foci Force Layout](https://gist.github.com/mbostock/1021953)
* [Clustered force layout](https://gist.github.com/mbostock/7881887)

**Comment by dfreeman06** [comment]
Is [d3.ForceBundle](https://github.com/upphiminn/d3.ForceBundle) a force simulation or separate edge routing given a particular node layout?

**Comment by nrbgt** [comment]
re: `forceBundle`: no idea. however we expose this, it should be composable with e.g. https://vasturiano.github.io/3d-force-graph/example/tree/

this might be something _separate_ from behaviors, e.g. `Layout`, `.layouts` or something
