### ISSUE TITLE
Return node position data

### ISSUE THREAD

**Issue by zwelz3** [jupyrdf/ipyforcegraph#30]
## Elevator Pitch

Method to return the current x,y (or x,y,z for 3D) positions of the graph nodes as a DataFrame. The node data on the frontend updates those field values when the forcegraph layout sim runs. It would be useful to return those positions. 

## Motivation

This would allow for better manual positioning of nodes between user interaction (e.g. reset-graph option without running sim), and potentially enable some interesting capability when toggling between 2D and 3D engines. 

## Design Ideas

Not sure how this would be connected to the sim process (i.e. requesting before sim runs/completes). 

N/A (at the moment)

**Comment by dfreeman06** [comment]
Is it also worth grabbing the velocities, `vx`, `vy`, `vz`?

**Comment by nrbgt** [comment]
> grabbing the velocities

I think it would just dump the entire `graphData` model, likely to another instance of `DataFrameSource`, so we can reuse all the compression stuff.

> when the forcegraph layout sim runs

As this can be a _lot_ of data (even just the `id`s and the positions), this probably needs to be similar to the `GraphImage` behavior, where a) it's opt-in and b) fires once. 60 frames a second (best case) would slow things down really bad. So `GraphData.sink` (or whatever) would be `None` until the `GraphData.capturing` flag is updated.
