### ISSUE TITLE
Heat/Reheat controls for ForceGraph

### ISSUE THREAD

**Issue by zwelz3** [jupyrdf/ipyforcegraph#36]
## Elevator Pitch

The ability to control the simulation heat/reheat parameters when making changes to the source and/or behaviors. A method for ex. pausing the simulation when applying certain style changes (e.g. node color), and a recommended design patter (within docs?) for how to achieve this desired effect. 

## Motivation

We are developing apps using ipyforcegraph, and updating this such as node/edge visibility, color, and other styles (as part of the ipyforcegraph supported behaviors) causes the visualization to "reheat" the graph layout. Under certain conditions it would be valuable to allow users of ipyforcegraph to control the heat settings so that operations can be performed on the source and behaviors without causing the visualization to reheat. A recommended implementation from the dev team will help ensure that the most effective manner for controlling these options is used downstream. 

## Design Ideas

Possibly set the config on the ForceGraph class (simplified e.g. `fg.reheat = False`) before modifying behaviors/source/etc.

**Comment by zwelz3** [comment]
Unsure how this is related to #28, but their may be some overlap.

**Comment by nrbgt** [comment]
Yerp, #28 (and by extension #35) probably handles this with the `GraphForcesBehavior.warmup_ticks` and `.cooldown_ticks`. The `Forces.ipynb` after [this build](https://readthedocs.org/projects/ipyforcegraph/builds/19424467/) should demonstrate it, with some more demo work under way.

We also clobbered a lot of jitter when various traits change, which should result in snappier updates.

**Comment by nrbgt** [comment]
https://ipyforcegraph--35.org.readthedocs.build/en/35/_static/lab/index.html?path=Forces.ipynb

(recommend opening this in a "private browsing" session so you don't get weird cache artifacts)

**Comment by nrbgt** [comment]
(also note that notebook is very much a work-in-progress... running past the couple cells right after _Warmup and Cooldown_ will blow away the linked configuration)

**Comment by nrbgt** [comment]
Fixed by #65
