### ISSUE TITLE
Visibility behavior

### ISSUE THREAD

**Issue by zwelz3** [jupyrdf/ipyforcegraph#37]
## Elevator Pitch

Ability to toggle node/link visibility (style method in `force-graph`) would be great. 

## Motivation

In conjunction with #36, this would allow filtering on node/edge, thereby reducing visual clutter, without causing significant layout changes. 

## Design Ideas

n/a

**Comment by nrbgt** [comment]
`NodeColors` and `LinkColors` can pretty much already do this. You could have a `column` that you updated from the backend, or a `template` that gets calculated off some other feature..

**Comment by zwelz3** [comment]
That would require storing the previous color in order to revert the visibility correct?

**Comment by zwelz3** [comment]
Or just change the alpha entry?

**Comment by nrbgt** [comment]
Consider a `LinkColor.template`:

```py
{{ link.color }}
```

Hiding them would just change the template to:

```py
rgba(0,0,0,0.0)
```

And then change it back when done.

**Comment by nrbgt** [comment]
Feel free to reopen if something more custom is required.
