### ISSUE TITLE
Camera Controls

### ISSUE THREAD

**Issue by dfreeman06** [jupyrdf/ipyforcegraph#47]
## Elevator Pitch

Better/smoother story telling through controlled panning and zooming on nodes / neighborhoods. 

## Motivation

Two things:
* Examples a model of the camera (e.i. what is the current view looking at)
* Moving the view to highlight a change from some other interactive elements.
    * Maybe two linked graphs where selecting a node in one moves the camera focus in the other.

## Design Ideas

Under https://github.com/vasturiano/force-graph#render-control there is a section that highlights several different camera control functions:
* centerAt([x], [y], [ms]) - getter and setter
* zoom([num], [ms]) - getter and setter
* zoomToFit([ms], [px], [nodeFilterFn])
* minZoom
* maxZoom

https://github.com/vasturiano/force-graph#utility
* getGraphBbox - could be combined with some other node checks to get a list of nodes currently in view of the camera. 

Other rendering functions that could be wrapped. Potentially for a follow on ticket. 
* autoPauseRedraw
* resumeAnimation
* pauseAnimation
* onRenderFramePre
* onRenderFramePost

**Comment by nrbgt** [comment]
Fixed by `v0.3.4`
