### ISSUE TITLE
Refactor Behaviors

### ISSUE THREAD

**Issue by sanbales** [jupyrdf/ipyforcegraph#57]
## Elevator Pitch

Refactor ``Behaviors`` to use the new ``Column`` and ``Nunjuck`` widgets, as developed in #54.

## Motivation

* This will make the behaviors more compact, and easier to use, and ultimately help new users understand how to use the library.
  * It will avoid issues with combining the individual behaviors, e.g., with the particles not displaying correctly unless they are all set to appropriate values.
  * Would make it easier to add validation to the results, helping users understand what values are not appropriate.

## Design Ideas

* Move away from the ``Behavior.(column_name|template)``, favoring dedicated widget subclasses ``Column`` and ``Nunjuck``.
  * Work a means to coerce values into an appropriate type for the output of ``Nunjuck`` templates, this will help make `falsey` python types evaluate to `false` in `js`
* Group behaviors into reasonable groups, e.g.,
  * ``NodeStyle`` combines ``NodeColors`` and ``NodeSizes``
  * ``LinkStyle`` combines ``LinkColors`` and ``LinkWidths``
  * ``LinkArrow`` combines ``LinkDirectionalArrowColor``, ``LinkDirectionalArrowLength``, and ``LinkDirectionalArrowRelPos``
  * ``LinkParticles`` combines ``LinkDirectionalParticleColor``, ``LinkDirectionalParticleSpeed``, ``LinkDirectionalParticleWidth``, amd ``LinkDirectionalParticles``
* Should we extend this pattern to `Forces`? It does not seem to be immediately relevant, but maybe there is a common way to think about them?
* If not, should we refactor the `python` API and put the `style` related behaviors in their own submodule, e.g., `ipyforcegraph/behaviors/style/` where we would have `node.py`, `link.py`, and `shape.py`?

**Comment by nrbgt** [comment]
I think the `*Style` would live under the `NodeShapes` and eventual `LinkShapes`

```py
NodeShapes(size=10, color="red")
```

These would be ignored entirely in the presence of `NodeShapes.shapes`, and/or be an a shortcut for an implicit `Circle`:

```py
NodeShapes(Circle(size=10, color="red"))
```
