### ISSUE TITLE
Adopt a `dev` branch workflow

### ISSUE THREAD

**Issue by nrbgt** [jupyrdf/ipyforcegraph#67]
## Elevator Pitch

Start a long-lived `dev` branch. Target `main` only with hotfixes, docs fixes, and releases. Target all other PRs on `main`.

## Motivation

This would simplify the binder badge situation, and make it a bit easier to have up-to-date dev docs for unreleased stuff, as well as the stable releases on PyPI.

## Design Ideas

- [x] create the long running branch
- [x] retarget open PRs to `dev`
- [ ] update `CONTRIBUTING.md` and `release.md` to reflect the changes
- [ ] ???

**Comment by sanbales** [comment]
I'm particular to ``dev`` exactly because of those two reasons, but not opposed to any of these, my preferences would be:
1. `dev`
2. `latest`
3. `develop`
4. `unreleased`
5. `working`

**Comment by nrbgt** [comment]
great, lets go with dev.

**Comment by nrbgt** [comment]
Fixed by #66
