### ISSUE TITLE
Retain node locations on new source

### ISSUE THREAD

**Issue by JoelStansbury** [jupyrdf/ipyforcegraph#80]
## Elevator Pitch
* When loading a new source that has some of the same nodes (by `ID`), have an option to retain their `x,y,z` location

## Motivation
* This can currently be done by getting the graph data on the python side, and including the `x,y,z` locations in the new dataframe and giving that back to `ipyforcegraph`. But this adds complexity and overhead to the process.

## Design Ideas
* Add a boolean trait to `forcegraph` that determines if node locations should be retained. `default=True`
* When creating new nodes on the [typescript side](https://github.com/jupyrdf/ipyforcegraph/blob/main/js/widgets/sources/dataframe.ts#LL163), try to set `x,y,z` (and `vx,vy,vz`?) if the node already exists.

**Comment by nrbgt** [comment]
Yeah, there are some very pointy edges to reusing existing nodes. still fighting it, nothing to demo.
