### ISSUE TITLE
Native continuous colorscales/colormaps

### ISSUE THREAD

**Issue by zwelz3** [jupyrdf/ipyforcegraph#83]
## Elevator Pitch
It would be extremely helpful if `ipyforcegraph` supported continuous colormaps (e.g. `viridis`) as part of the Nunjucks templating. Users would be able to specify columns that contain continuous values (age, weight, etc.) and a colormap, and `ipyforcegraph` would be able to apply the color as part of the e.g. NodeShape behavior without requiring additional dependencies i.e. `matplotlib`. 

## Motivation
Bringing in additional dependencies to support styling with `ipyforcegraph` can complicate build chains, recipes, etc. It would be valuable to reduce complexity of leveraging ipyforcegraph to include common colormaps for continuous values, which are more complicated to implement than discrete maps (which can be easily added with e.g. dictionaries). 

## Design Ideas

Something akin to `{{ node.value | colormap('viridis') }}` would be extremely powerful.

**Comment by nrbgt** [comment]
From a discussion offline: adding more complexity to `Nunjucks` would likely hurt performance/debuggability. 

[bqscales](https://github.com/bqplot/bqscales) exists, but might not do what we want. 

If we have to implement it full-cloth, we would likely still lean on the d3 ecosystem, such as [d3-scale-chromatic](https://github.com/d3/d3-scale-chromatic), as a new sibling to `Nunjucks` and `Column`.

As a strawman:

```py
node_shape.color = ColorScale(
    column_name="value",
    min=fg.source.nodes.value.min(),
    max=fg.source.nodes.value.max(),
    named_scheme=ScaledColumn.COLORS.viridis
)
```

Probably have some other approaches for arbitrary values (e.g. `domain=["red", "blue"]`).

This may entail some lower-level `Scale` which can handle different kinds of things.
