### ISSUE TITLE
Occasional incorrect sorting of nodes when using preserve columns

### ISSUE THREAD

**Issue by sanbales** [jupyrdf/ipyforcegraph#90]
## Description

Graphs that use id's that can be coerced into numbers, get their `nodes` and `links` sorted when the preserve columns functionality is used, breaking the indexing used by the `NodeSelection` and `LinkSelection`.

## Reproduce

```python
import json
from pathlib import Path
from time import sleep

import ipyforcegraph.graphs as G
import ipyforcegraph.sources as S
import ipyforcegraph.behaviors as B

source_data = json.loads(Path("./datasets/blocks.json").read_text())

source = S.DataFrameSource(
    **source_data,
    node_preserve_columns=["x", "y"],
)

selection, get_data = behaviors = [
    B.NodeSelection(column_name="_selected"),
    B.GraphData(),
]

fg = G.ForceGraph(
    source=source,
    behaviors=behaviors,
    layout=dict(height="100%"),
)

# select a node
selection.selected = [850]

# capture data from front-end
get_data.capturing = True

# compare id of selected node as per the backend and the frontend
# note: need to add appropriate async awaits for this to work
id_per_backend_source = source.nodes.id[selection.selected[0]]

frontend_nodes_data = get_data.sources[0].nodes
id_per_frontend_source = frontend_nodes_data.id[frontend_nodes_data._selected == True].iloc[0]

# this assert fails
assert id_per_backend_source == id_per_frontend_source

# as does this one:
assert tuple(source.nodes.id) == tuple(frontend_nodes_data.id)
```

## Expected behavior

Would have expected the nodes to be in the same order as that is what the `NodeSelection` and `LinkSelection` use.

## Context

Believe the issue is that `Object.values` (used [here](https://github.com/jupyrdf/ipyforcegraph/blob/dfddd9f3b9aea04b2004af174459595f4a4e7b9c/js/widgets/sources/dataframe.ts#L275)) [sorts the results by the keys if those can be coerced into numbers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values#using_object.values), and because in this example some of the keys can be while others are alphanumeric, some nodes show up in a different order in the front-end vs the back-end.  This can also be verified by looking at the order of the `nodes` dataframe retrieved by `GraphData`, which may be a better test.  Also manually prepended `"_"` to all the `id`s in the graph and the issue did not pop up.

- Operating System and version: Windows 10
- Browser and version: Chrome 113.0.5672.93 (Official Build) (64-bit)
- JupyterLab version: 3.6.3
- IPyForceGraph version(s): 0.3.2

<details><summary>Required: installed server extensions</summary>
<pre>
Config dir: C:\Users\sb282\.jupyter

Config dir: C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\etc\jupyter
    jupyter_server_fileid enabled
    - Validating jupyter_server_fileid...
Package jupyter_server_fileid took 0.0117s to import
      jupyter_server_fileid 0.9.0 ok
    jupyter_server_terminals enabled
    - Validating jupyter_server_terminals...
Package jupyter_server_terminals took 0.0412s to import
      jupyter_server_terminals 0.4.4 ok
    jupyter_server_ydoc enabled
    - Validating jupyter_server_ydoc...
Package jupyter_server_ydoc took 0.3604s to import
      jupyter_server_ydoc 0.8.0 ok
    jupyterlab enabled
    - Validating jupyterlab...
Package jupyterlab took 0.3751s to import
      jupyterlab 3.6.3 ok
    jupyterlab_link_share enabled
    - Validating jupyterlab_link_share...
Package jupyterlab_link_share took 0.3288s to import
      jupyterlab_link_share 0.2.5 ok
    nbclassic enabled
    - Validating nbclassic...
Package nbclassic took 0.0000s to import
A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      nbclassic 1.0.0 ok
    notebook_shim enabled
    - Validating notebook_shim...
Package notebook_shim took 0.0000s to import
A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      notebook_shim  ok

Config dir: C:\ProgramData\jupyter
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
        bqplot v0.5.40 enabled ok (python, bqplot)
        ipydatagrid v1.1.15 enabled ok
        ipylab v0.7.1 enabled ok (python, ipylab)
        jupyterlab-link-share v0.2.5 enabled ok (python, jupyterlab-link-share)
        jupyterlab_pygments v0.2.2 enabled ok (python, jupyterlab_pygments)
        @deathbeds/jupyterlab-deck v0.1.3 enabled ok
        @deathbeds/jupyterlab-font-anonymous-pro v2.1.1 enabled ok (python, jupyterlab-fonts)
        @deathbeds/jupyterlab-font-dejavu-sans-mono v2.1.1 enabled ok (python, jupyterlab-fonts)
        @deathbeds/jupyterlab-font-fira-code v2.1.1 enabled ok (python, jupyterlab-fonts)
        @deathbeds/jupyterlab-fonts v2.1.1 enabled ok (python, jupyterlab-fonts)
        @jupyrdf/jupyter-forcegraph v0.3.2 enabled ok
        @jupyter-widgets/jupyterlab-manager v5.0.7 enabled ok (python, jupyterlab_widgets)
        @jupyterlite/pyodide-kernel-extension v0.0.8 enabled ok (python, jupyterlite_pyodide_kernel)
</pre>
</details>

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\Library\mingw-w64\bin
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\Library\usr\bin
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\Library\bin
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\Scripts
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\bin
        C:\mf\envs\doit\condabin
        C:\Program Files (x86)\Integrity\ILMClient11.2\bin
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0
        C:\WINDOWS\System32\OpenSSH
        C:\PROGRA~2\INTEGR~1\Toolkit\mksnt
        C:\Program Files (x86)\Webex\Plugins
        C:\HashiCorp\Vagrant\bin
        C:\Program Files\Docker\Docker\resources\bin
        C:\ProgramData\DockerDesktop\version-bin
        C:\Program Files\RedHat\java-14-openjdk-14.0.1-1\bin
        C:\Program Files\MATLAB\R2021b\bin
        .
        C:\Program Files\RedHat\Podman
        C:\Users\sb282\AppData\Local\Microsoft\WindowsApps
        C:\Users\sb282\AppData\Local\Programs\Microsoft VS Code\bin
        C:\Program Files\Java\jdk-13\bin
        C:\Gradle\gradle-6.5.1\bin
        C:\Users\sb282\AppData\Local\Programs\Git\cmd

sys.path:
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\Scripts
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\python311.zip
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\DLLs
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\Lib
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\Lib\site-packages
        C:\sandboxes\ipyforcegraph\src
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\Lib\site-packages\win32
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\Lib\site-packages\win32\lib
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\Lib\site-packages\Pythonwin

sys.executable:
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\python.exe

sys.version:
        3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:50:54) [MSC v.1934 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.19045-SP0

where jupyter:
        C:\sandboxes\ipyforcegraph\envs\py3.11_lab3.6\Scripts\jupyter.exe

pip list:
        Package                        Version     Editable project location
        ------------------------------ ----------- --------------------------
        accessible-pygments            0.0.4
        aiofiles                       22.1.0
        aiosqlite                      0.19.0
        alabaster                      0.7.13
        ansi2html                      0.0.0
        anyio                          3.6.1
        argon2-cffi                    21.3.0
        argon2-cffi-bindings           21.2.0
        asttokens                      2.2.1
        async-generator                1.10
        attrs                          23.1.0
        autodoc-traits                 1.1.0
        autopep8                       2.0.2
        Babel                          2.12.1
        backcall                       0.2.0
        backports.functools-lru-cache  1.6.4
        beautifulsoup4                 4.12.2
        black                          23.3.0
        bleach                         6.0.0
        bqplot                         0.12.39
        brotlipy                       0.7.0
        cattrs                         22.2.0
        certifi                        2023.5.7
        cffi                           1.15.1
        charset-normalizer             3.1.0
        click                          8.1.3
        cloudpickle                    2.2.1
        cmarkgfm                       0.8.0
        colorama                       0.4.6
        comm                           0.1.3
        coverage                       7.2.5
        cryptography                   40.0.2
        debugpy                        1.6.7
        decorator                      5.1.1
        defusedxml                     0.7.1
        docutils                       0.19
        doit                           0.36.0
        entrypoints                    0.4
        exceptiongroup                 1.1.1
        execnet                        1.9.0
        executing                      1.2.0
        fastjsonschema                 2.16.3
        flit                           3.8.0
        flit_core                      3.8.0
        gast                           0.4.0
        greenlet                       2.0.2
        h11                            0.14.0
        html5lib                       1.1
        idna                           3.4
        imagesize                      1.4.1
        importlib-metadata             6.6.0
        importlib-resources            5.12.0
        importnb                       2023.1.7
        iniconfig                      2.0.0
        ipydatagrid                    1.1.15
        ipyforcegraph                  0.3.2       C:\sandboxes\ipyforcegraph
        ipykernel                      6.23.0
        ipylab                         0.7.1
        ipython                        8.13.2
        ipython-genutils               0.2.0
        ipywidgets                     8.0.6
        itsdangerous                   2.1.2
        jaraco.classes                 3.2.3
        jedi                           0.18.2
        Jinja2                         3.1.2
        json5                          0.9.5
        jsonschema                     4.17.3
        jupyter-cache                  0.6.1
        jupyter_client                 8.2.0
        jupyter_core                   5.3.0
        jupyter-events                 0.6.3
        jupyter_server                 2.5.0
        jupyter_server_fileid          0.9.0
        jupyter_server_terminals       0.4.4
        jupyter_server_ydoc            0.8.0
        jupyter-ydoc                   0.2.3
        jupyterlab                     3.6.3
        jupyterlab-deck                0.1.3
        jupyterlab-fonts               2.1.1
        jupyterlab-link-share          0.3.0
        jupyterlab-pygments            0.2.2
        jupyterlab_server              2.22.1
        jupyterlab-widgets             3.0.7
        jupyterlite-core               0.1.0
        jupyterlite-pyodide-kernel     0.0.8
        keyring                        23.13.1
        libarchive-c                   4.0
        livereload                     2.6.3
        lxml                           4.9.2
        markdown-it-py                 2.2.0
        MarkupSafe                     2.1.2
        matplotlib-inline              0.1.6
        mdit-py-plugins                0.3.5
        mdurl                          0.1.0
        mistune                        2.0.5
        more-itertools                 9.1.0
        msgpack                        1.0.5
        mypy                           1.2.0
        mypy-extensions                1.0.0
        myst-nb                        0.17.2
        myst-parser                    0.18.1
        natsort                        8.3.1
        nbclassic                      1.0.0
        nbclient                       0.7.4
        nbconvert                      7.4.0
        nbformat                       5.8.0
        nbqa                           1.7.0
        nbstripout                     0.6.1
        nest-asyncio                   1.5.6
        networkx                       3.1
        notebook                       6.5.4
        notebook_shim                  0.2.3
        numcodecs                      0.11.0
        numpy                          1.24.3
        orjson                         3.8.12
        outcome                        1.2.0
        packaging                      23.1
        pandas                         2.0.1
        pandocfilters                  1.5.0
        parso                          0.8.3
        pathspec                       0.11.1
        pickleshare                    0.7.5
        pip                            23.1.2
        pkginfo                        1.9.6
        pkgutil_resolve_name           1.3.10
        platformdirs                   3.5.0
        pluggy                         1.0.0
        prometheus-client              0.16.0
        prompt-toolkit                 3.0.38
        psutil                         5.9.5
        pure-eval                      0.2.2
        py                             1.11.0
        py2vega                        0.6.1
        pycodestyle                    2.10.0
        pycparser                      2.21
        pydata-sphinx-theme            0.13.3
        Pygments                       2.15.1
        pyOpenSSL                      23.1.1
        pyproject-fmt                  0.11.2
        pyrsistent                     0.19.3
        PySocks                        1.7.1
        pytest                         7.3.1
        pytest-asyncio                 0.21.0
        pytest_check_links             0.8.0
        pytest-cov                     4.0.0
        pytest-html                    3.2.0
        pytest-json-report             1.5.0
        pytest-metadata                2.0.4
        pytest-xdist                   3.2.1
        python-dateutil                2.8.2
        python-json-logger             2.0.7
        pytz                           2023.3
        pywin32                        304
        pywin32-ctypes                 0.2.0
        pywinpty                       2.0.10
        PyYAML                         6.0
        pyzmq                          25.0.2
        readme-renderer                37.3
        requests                       2.29.0
        requests-cache                 1.0.1
        requests-toolbelt              1.0.0
        rfc3339-validator              0.1.4
        rfc3986                        2.0.0
        rfc3986-validator              0.1.1
        rich                           13.3.5
        rich-click                     1.6.1
        robotframework                 6.0.2
        robotframework-jupyterlibrary  0.4.2
        robotframework-pabot           2.15.0
        robotframework-pythonlibcore   4.1.2
        robotframework-robocop         3.1.1
        robotframework-seleniumlibrary 6.1.0
        robotframework-stacktrace      0.4.1
        robotframework-tidy            4.2.1
        ruff                           0.0.265
        scour                          0.38.2
        selenium                       4.9.1
        Send2Trash                     1.8.2
        setuptools                     67.7.2
        six                            1.16.0
        sniffio                        1.3.0
        snowballstemmer                2.2.0
        sortedcontainers               2.4.0
        soupsieve                      2.3.2.post1
        Sphinx                         5.3.0
        sphinx-autobuild               2021.3.14
        sphinx_autodoc_typehints       1.21.8
        sphinx-copybutton              0.5.2
        sphinxcontrib-applehelp        1.0.4
        sphinxcontrib-devhelp          1.0.2
        sphinxcontrib-htmlhelp         2.0.1
        sphinxcontrib-jsmath           1.0.1
        sphinxcontrib-qthelp           1.0.3
        sphinxcontrib-serializinghtml  1.1.5
        SQLAlchemy                     2.0.12
        ssort                          0.11.6
        stack-data                     0.6.2
        stringcase                     1.2.0
        tabulate                       0.9.0
        terminado                      0.17.0
        tinycss2                       1.2.1
        tokenize-rt                    5.0.0
        toml                           0.10.2
        tomli                          2.0.1
        tomli_w                        1.0.0
        tomlkit                        0.11.8
        tornado                        6.3
        traitlets                      5.9.0
        traittypes                     0.2.1
        trio                           0.22.0
        trio-websocket                 0.10.2
        twine                          4.0.2
        typing_extensions              4.5.0
        tzdata                         2023.3
        ujson                          5.7.0
        url-normalize                  1.4.3
        urllib3                        1.26.15
        wcwidth                        0.2.6
        webencodings                   0.5.1
        websocket-client               1.5.1
        wheel                          0.40.0
        widgetsnbextension             4.0.7
        win-inet-pton                  1.1.0
        wsproto                        1.2.0
        y-py                           0.5.9
        ypy-websocket                  0.8.2
        zipp                           3.15.0
</pre>
</details>

**Comment by nrbgt** [comment]
fixed with tests on #91
