### ISSUE TITLE
node_preserve_columns does not work as expected

### ISSUE THREAD

**Issue by JoelStansbury** [jupyrdf/ipyforcegraph#99]
## Description

If node_preserve_columns is provided, then altering source.nodes results in an empty viewport.
I may also be using a bad update procedure (this is just the process that has worked for me in previous versions)

![chrome_RyTkabqo9G](https://github.com/jupyrdf/ipyforcegraph/assets/48299585/64467b0b-7120-4f92-b77a-f12f6dd8b504)

## Reproduce

1. Create a ForceGraph with node_preserve_columns
2. Provide nodes and links to source
3. Remove a node (and any links connected to it)

```python
from ipyforcegraph.graphs import ForceGraph
from ipyforcegraph.sources import DataFrameSource
from IPython.display import display
from ipywidgets import Box
import pandas as pd
import time
source = DataFrameSource(
    node_preserve_columns = ["x", "y", "_selected"]
)
g = ForceGraph(source=source)
display(Box([g], layout={"height":"400px"}))
source.nodes = pd.DataFrame(
    [
        {"id":1},
        {"id":2},
        {"id":3},
        {"id":4},
    ]
)
source.links = pd.DataFrame(
    [
        {"source":2, "target":3},
    ]
)
time.sleep(0.5)
source.nodes = pd.DataFrame(
    [
        # {"id":1},  # Remove a node to alter the graph
        {"id":2},
        {"id":3},
        {"id":4},
    ]
)
```

## Expected behavior
This is how ipyforcegraph v0.3.2 behaves.
When node_preserve_columns is set to [x,y,_selected], updating the nodes dataframe does not result in an empty viewport

![chrome_syKwPQd4W6](https://github.com/jupyrdf/ipyforcegraph/assets/48299585/fe7fa40d-7a1c-4518-8107-87e110921a33)

## Context

- Operating System and version: Windows
- Browser and version: Chrome Version 114.0.5735.134 (Official Build) (64-bit)
- JupyterLab version: 3.6.4
- IPyForceGraph version(s): 0.3.3

<details><summary>Required: installed server extensions</summary>
<pre>
config dir: ...\.envs\dev\etc\jupyter
    jupyter_server_ydoc enabled
    - Validating...
      X is jupyter_server_ydoc importable?
    jupyterlab enabled
    - Validating...
      jupyterlab 3.6.4 ok
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
JupyterLab v3.6.4
...\.envs\dev\share\jupyter\labextensions
        bqplot v0.5.40 enabled ok (python, bqplot)
        ipydatagrid v1.1.16 enabled ok
        ipylab v0.7.1 enabled ok (python, ipylab)
        ipytree v0.2.2 enabled ok
        jupyterlab_pygments v0.2.2 enabled ok (python, jupyterlab_pygments)
        @jupyrdf/jupyter-forcegraph v0.3.2 enabled ok (it's v0.3.3, this output was gathered after installing 0.3.2 to make the expected gif)
        @jupyter-widgets/jupyterlab-manager v5.0.5 enabled ok (python, jupyterlab_widgets)
</pre>
</details>

<details><summary>Troubleshoot Output</summary>
<pre>
  Paste the output from running `jupyter troubleshoot` from the command line here.
  You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
  Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output (recommended for all interface issues)</summary>
<pre>
  Paste the output from your browser JavaScript console replacing the text in here.

To learn how to open the developer tools in your browser:
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#How_to_open_the_devtools_in_your_browser
If too many messages accumulated after many hours of working in JupyterLab, consider
refreshing the window and then reproducing the bug to reduce the noise in the logs.

</pre>
</details>

**Comment by nrbgt** [comment]
Might be a tick before I can get to it... that very last template item (_Browser Output_) is pretty darned useful, however.

**Comment by nrbgt** [comment]
Have a fix up (in 8eb28908f8c9c0a4ab840b3b37568585a8c2bd02) on #98, which can be tried out with the above code on:

https://ipyforcegraph--98.org.readthedocs.build/en/98/_static/lab/index.html

**Comment by JoelStansbury** [comment]
Awesome! Thank you @nrbgt

**Comment by nrbgt** [comment]
Please have a look at `0.3.4` and see if this resolves the issue. :fireworks:

**Comment by JoelStansbury** [comment]
> Please have a look at `0.3.4` and see if this resolves the issue. 🎆

Testing on ipyforcegraph-0.3.4-pyhd8ed1ab_0
Can confirm that the issue is resolved.
Thanks Nick!
